ARDUINO_DIR  = /usr/share/arduino
# ARDUINO_PORT = /dev/ttyACM0

USER_LIB_PATH = ~/sketchbook/libraries

BOARD_TAG    = mega
BOARD_SUB    = atmega2560
MONITOR_PORT = /dev/ttyACM0
ARDUINO_DIR  = /where/you/installed/arduino-1.6.5
include /usr/share/arduino/Arduino.mk

include /usr/share/arduino/Arduino.mk
