ARDUINO_DIR  = /usr/share/arduino
# ARDUINO_PORT = /dev/ttyACM0

USER_LIB_PATH = ~/sketchbook/libraries

BOARD_TAG    = mega
BOARD_SUB    = atmega2560
MONITOR_PORT = /dev/ttyACM*

include /usr/share/arduino/Arduino.mk
