[package]
name = "raspPins"
version = "0.1.0"
authors = ["Jacob Montpetit <vikingfacer@users.noreply.github.com>"]

[dependencies]
rust-pigpio = "0.2.0"
libc ="0.2"
i2cdev = "0.3.1"
spidev = "0.3.0"

magnetic = "2.0.0"